server:
  port: 9090
  servlet:
    context-path: /api/v1/account
spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    org.springframework.security: OFF

